import Head from 'next/head';
import Image from 'next/image';
import Nav from '@/components/Nav';

export default function Home() {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full w-full  flex flex-col items-center">
        <Nav />
        <section className="w-full h-full flex flex-col items-center"></section>
      </main>
    </div>
  );
}
