import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { SlSocialGithub, SlSocialTwitter } from "react-icons/sl";
import axios from "axios";

import Post from "@/components/post";

import { IDevtoPost } from "@/types/devto";

export async function getServerSideProps() {
	const res = await axios.get(
		"https://dev.to/api/articles?username=suiteasdesign"
	);
	return {
		props: {
			posts: res.data as IDevtoPost[],
		},
	};
}

export default function Home({ posts }: { posts: IDevtoPost[] }) {
	return (
		<div className="w-screen md:h-screen">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="h-full w-full items-center">
				<div className="w-full md:h-full grid grid-cols-1 grid-rows-2 md:grid-cols-2 md:grid-rows-1 md:w-full ">
					<section className=" flex items-center pb-8 pt-20">
						<div className="flex flex-col items-center">
							<Image
								src="/aodhan.png"
								alt="aodhan in dress shirt in garden smiling"
								width="100"
								height="100"
								className="border rounded-full w-24 md:w-36  "
								priority={true}
							/>
							<h1 className="text-2xl mt-1">Aodhan Hamilton</h1>
							<span className="mt-2 text-base italic text-center">
								Developer & Digital Assistant at
								<span className="px-1">
									<Link href="https://www.learnwithjason.dev/">
										Learn with Jason
									</Link>
								</span>
							</span>

							<div className="flex justify-around w-20 mt-1 ">
								<Link href="https://twitter.com/mvaodhan">
									<SlSocialTwitter
										color="teal"
										style={{ width: "25px", height: "25px" }}
									/>
								</Link>

								<Link href="https://github.com/MVAodhan">
									<SlSocialGithub style={{ width: "25px", height: "25px" }} />
								</Link>
							</div>

							<p className="mt-1 w-4/5 text-sm md:text-xl lg:w-3/5 text-center">
								I&#x27;m a JavaScript and TypeScript enthusiast. Constantly
								learning and building with my new-found knowledge, excites me. I
								love working on technical solutions, to solve real-world
								problems, be them for myself, or others.
							</p>
						</div>
					</section>
					<section className="w-full h-full flex flex-col items-center justify-center">
						<div className="w-11/12 md:h-4/5 flex flex-col items-center">
							{posts.map((post) => (
								<Post key={post.id} post={post} />
							))}
						</div>
					</section>
				</div>
			</main>
		</div>
	);
}
