import Head from 'next/head';
import Image from 'next/image';
import Nav from '@/components/Nav';
import Link from 'next/link';
import { SlSocialGithub, SlSocialTwitter } from 'react-icons/sl';

export default function Home() {
  return (
    <div className="w-screen h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full w-full  flex flex-col items-center">
        <Nav />
        <section className="w-full h-full flex flex-col items-center">
          <Image
            src="/aodhan.png"
            alt="aodhan in dress shirt in garden smiling"
            width="200"
            height="200"
            className="border rounded-full mt-32 w-24 sm:w-36 md:w-44"
            priority={true}
          />
          <h1 className="text-2xl mt-6">Aodhan Hamilton</h1>
          <span className="mt-2 text-lg italic text-center">
            Developer & Learn with Jason Digital Assistant
          </span>

          <div className="flex justify-around w-20 mt-4 ">
            <Link href="https://twitter.com/suiteasdesign">
              <SlSocialTwitter
                color="teal"
                style={{ width: '25px', height: '25px' }}
              />
            </Link>

            <Link href="https://github.com/MVAodhan">
              <SlSocialGithub style={{ width: '25px', height: '25px' }} />
            </Link>
          </div>

          <p className="mt-4 w-4/5 text-sm sm:text-xl lg:w-3/5 text-center">
            When I'm not scheduling or uploading
            <span className="px-1">
              <Link href="https://www.learnwithjason.dev/">
                Learn with Jason
              </Link>
            </span>
            episodes, I'm building things and experimenting in JavaScript and
            TypeScript. I love building with Next.JS and using serverless
            technologies the most.
          </p>
        </section>
      </main>
    </div>
  );
}
